version: '3.4'

services:
  angular:
    build:
      context: .
      dockerfile: Dockerfile
    image: pangea-ui
    container_name: pangea-ui
    ports:
      - "4200:4200"
    volumes:
      - '.:/app'
      - '/app/node_modules'
networks:
  dev-network:
    driver: bridge


